### PR TITLE
New Razor-Tag with option z

### PR DESCRIPTION
**Pull request by loh-tar**
Everyone is invited to try it out and report issues, ideas or suggestions.

### CODE REVIEW

**Comment by loh-tar** [comment]
I think the new Razor tags are not so bad. 
However, there is now the problem that unnecessary blank lines can remain at the top or bottom of the resulting file.

**Comment by vidy007** [comment]
on my way to rewrite tizu structure from scratch for testing

**Comment by loh-tar** [comment]
Just check this branch out, and play around. If all works as it should. Tell me what you think about any bad change you notice. These naming rules are perhaps less useful than intended.

**Comment by loh-tar** [comment]
Now in master 803f302

**Pull request closed without merging**
