### PR TITLE
Add Debian logo

### PR DESCRIPTION
**Pull request by vidy007**

### CODE REVIEW

**Comment by loh-tar** [comment]
Hi guys! Phew! After seven years I have to see how to handle this new stuff...

Thanks for your interest and contribution, the first impression looks really nice!

Here what hit my eyes

- The Desc= could be more precise. Has these Debian helix/curl some special name? These lettering is really big. How about "Big 17 line debian logo and lettering"?
- How about some more color options/sets?
- Are these trailing spaces needed?
- It would be nice to adjust the file with some blanks so that it is more human friendly, see 4-3- in Manual
- I would prefer to have only one commit (or max two with a reasonable message), I can squash them if you like but then may artem credits are gone

**Comment by vidy007** [comment]
Hello! Thanks for replying and not archiving this project. I agree with
your suggestions and will add them, but i don't understand the last one.
What do you mean by "the credits will be gone"? Also, these commits were
made by a small accident called my inattention. I dunno how to get rid of
them now.

sun, 27 oct. 2024 г., 22:40 loh-tar ***@***.***>:

**Comment by loh-tar** [comment]
> What do you mean by "the credits will be gone"? 

Then there would be only one commit with author vidy, the "third/forth" was author artem. But that's you too?

> I dunno how to get rid of them now. 

You can squash them by you own or *soft* reset your work/commits and make a new one. You can play local with a new branch without the risk to lost something.

After that force push. Well, I don't know  what then happens with this PR ... guess it will work but you may look at the docu

**Comment by vidy007** [comment]
Ah, I see. I'll just reset them and make a new one. What's interesting is
that the commits author's name is my __local__ account's nickname, not my
GitHub's one.

вс, 27 окт. 2024 г., 23:05 loh-tar ***@***.***>:

**Comment by loh-tar** [comment]
You need to config git as you want it. Currently looks the vidy email a little strange.
Btw, these squash is done by git rebase command.

**Pull request closed without merging**
