### PR TITLE
Add privilege binary switch

### PR DESCRIPTION
**Pull request by J-D-Wifi-08**
Current behaviour uses sudo to escalate privileges, however some distributions use doas. 

This fixes that behaviour.

### CODE REVIEW

**Comment by loh-tar** [comment]
Hello, thanks for your contribution!

Your solution is obvious, and certainly does not worsen the situation :-)

To be honest, I don't know if this feature is so smart and should be kept or if we should simply ask the user to execute the command again with the necessary rights. I have searched in vain for a generally valid solution, some standard, but have found nothing. Maybe I wasn't looking with the right words.

There are some problems with the current solution.

- What if the user is already root
- What if no sodu nor doas but run0 is configured (have heard there is some new stuff) or anything else
- Are these hard-coded paths bulled proof? 

Should we continue here, I would suggest to 

- fetch the path and program name by "command -v" and test then with -x instead, see https://stackoverflow.com/a/677212
- I somehow don't like this name _privUtil_ I first think of private instead of privilege :-/ Pls. find something nicer...maybe _getRootPower_ _runAsRoot_ I don't know. 
- remove the corresponding line in ToDo file

**Comment by J-D-Wifi-08** [comment]
Definitely some valid critiques of my solution. I haphazardly threw it together, since i don't use sudo. 

I agree on potentially adding some further checks regarding whether the user is root or not. Not actually heard of run0 myself so will have to look into it. From my perspective, id say it should not be made more complex than it needs to be. If their are 2 or 3 main privilege binaries to get UID 0, then i don't see the issue hard coding them in. 

The "command -v" route could be a good way to get around it. From a security perspective, i much prefer it over just running tulizu as root in the first place.

**Comment by loh-tar** [comment]
> From my perspective, id say it should not be made more complex than it needs to be. 

yes

> If their are 2 or 3 main privilege binaries to get UID 0, then i don't see the issue hard coding them in.

guess, until there is some (new) kind of standard, like EDITOR env var, we need to do it

> From a security perspective, i much prefer it over just running tulizu as root in the first place.

good point!

Regarding your latest changes, I am not so happy yet. But I also don't want to get on your nerves unnecessarily. So if you have enough other things to do, that's completely understandable. I think it's in your interest if I add the few lines of code myself,  don't you?

**Comment by J-D-Wifi-08** [comment]
Completely understandable if you are not quite happy with it. Feel free to make changes as you'd like (I'm more leaning towards closing this - see below).

Even though I mentioned ideally you wouldn't run tulizu as root, the more I've thought about it I don't think there's any way around it. The only reason i made the initial PR in the first place was because sudo was mentioned directly in the code and it breaks if not present (I thought it was a design choice from your perspective). 

The nature of tulizu being a bash script that requires UID 0 within certain functions means the complexity of the script will grow depending on how many other new user change utilities are developed. This obviously could mean the complexity of the initial function could grow much longer and messy code is not fun.

I think the only elegant solution to the problem, is to prevent it from happening at all. Instead an error or prompt should be printed after checking if UID != 0 and telling the user to run the script as root. Yes, security wise it can be problematic taking this stance, however since bash is constrained when elevating privileges effectively the only way i can see it from being solved is to just force the user to run it as root. :/

I'll keep the PR open if you want to make changes and i do not mind still being involved, its just my opinion on how to solve the issue has now changed. :)

**Comment by loh-tar** [comment]
There should be now a power-escalation branch. Pls take look at it, if you find something problematic.

Yeah, it's all tricky. No matter what you do, there are always good reasons against it :-)
But the concept of an application asking for extra rights for certain things is well established. So I think we're on the right track.

**Comment by J-D-Wifi-08** [comment]
Clean solution. Looks good to me. Much more effort than what i implemented, but i was unsure about how to fully tackle it. 

Either way tested and resolves the underlying issue that i had and adds an easy mechanism for further additions.

**Comment by loh-tar** [comment]
Thanks for trying and the feedback! 
I'll let it rest for a few more days. Maybe I'll notice something if I play around with it a bit longer. I've hardly tried it out.

**Pull request closed without merging**
