### PR TITLE
Add Debian logo

### PR DESCRIPTION
**Pull request by vidy007**
Hello! I saw this great project a while ago and was using it with my arch. Recently, i switched to Debian and noticed that there's no logo for this distro. So i decided to add it. The logo has three color schemes:

- Original (white with red swirl logo debris and "i" point)

- Magenta (same as original but magenta colors)

- White (white lol)

logo-only/lettering-only/etc. variants are in progress already :)

### CODE REVIEW

**Comment by vidy007** [comment]
i couldn't get rid of previous commits, so there are some trash names, sorry

**Comment by loh-tar** [comment]
> i couldn't get rid of previous commits, so there are some trash names, sorry

Try this (if in doubt on an other branch)

```
git reset d7ee6ae
git add tizu/debian-logo-large.tizu
git commit
```

- Is *arten* then the ID do you want to use or something with *vidy*? If not edit your `~/.gitconfig`
- Two more sets are nice, but the difference is really small :-) But OK, I will not insist to be more creative
- Desc looks buggy to me but my english is bad...
- Would be really nice if the file would be adjusted as mentioned earlier

> logo-only/lettering-only/etc. variants are in progress already :)

That's nice! :-)

**Comment by vidy007** [comment]
If not editing the config, I prefer to use my GitHub name (vidy). Also, im
cleaning the logo right now, soon I will make a push :)

пн, 28 окт. 2024 г., 22:04 loh-tar ***@***.***>:

**Comment by vidy007** [comment]
Done cleaning!
 btw, username in .gitconfig is vidy, like here, but commits are still done by "artem"... strange

**Comment by loh-tar** [comment]
> btw, username in .gitconfig is vidy, like here, but commits are still done by "artem"... strange

Hm, git has multiple places to config, IIRC looks git from project recursive back to root of home for config files. Ask some search service how to config

**Comment by loh-tar** [comment]
Let's keep it open.

**Comment by vidy007** [comment]
nuked the fork so issue is closed, opening a new one

**Pull request closed without merging**
