### PR TITLE
Add Debian logo (+logo-only and lettering-only)

### PR DESCRIPTION
**Pull request by vidy007**
Hello! Finally got along with those commits (simply by nuking my fork lmao)
There are 3 variations of the logo:
- Large (logo + lettering)
- Logo-only
- Lettering only
Each of them has many colorsets, somewhere around 6-8. Hope the logo looks good :)

### CODE REVIEW

**Comment by loh-tar** [comment]
I assume you didn't make these logo and lettering from scratch. Are there some guys who should be noted, or a link where you find it?

**Comment by vidy007** [comment]
no, i just used text/image to ASCII generators, no stealing :)

сб, 2 нояб. 2024 г., 03:20 loh-tar ***@***.***>:

**Comment by vidy007** [comment]
Next variations (small logo and lettering) will be done clearly by me from
zero

сб, 2 нояб. 2024 г., 11:38 Артём Потеряев ***@***.***>:

**Comment by loh-tar** [comment]
Oh, wow!  Well done!
So, is this a figlet font? Then may that name good to know, perhaps as file-name or description.
The commit message may contain detailed information, like used tools.
BTW, one commit per file would be nice.

**Comment by vidy007** [comment]
Honestly i dont know what this font is exactly, so ill just add this name to the desc.
Speaking of commits, this is much better than before, don't you think? :)

**Comment by vidy007** [comment]
By the way, i probably found the creator of the swirl logo. It may be https://github.com/CarterLi, but i'm not sure.

**Comment by vidy007** [comment]
Almost done with the small variations. I have 2 versions of this. Which one is better?
https://github.com/user-attachments/assets/72e3708c-ba31-422c-ae08-9d26178548ac


> So, is this a figlet font?
This is "Doh", the converter i use says

**Comment by loh-tar** [comment]
For me the lower one, but the upper has less hight and one may like that. I see no need to add one and the other not. So just add both :-)

**Comment by vidy007** [comment]
Got it!

сб, 2 нояб. 2024 г., 19:06 loh-tar ***@***.***>:

**Comment by vidy007** [comment]
whoops

**Comment by vidy007** [comment]
there are two similar commits because of silly ".tizu_" temp files that i didn't delete earlier

**Comment by loh-tar** [comment]
Just a quick feedback, I haven't tried much.
 
> there are two similar commits because of silly ".tizu_" temp files that i didn't delete early

No problem. We can fix this later

- I like the new smaller ones :-)
- Commit ID is now artem and author vidy007. I'm ok with that, if it is what you want. But..?
- debian-small-logo-lettering is kind of surprising. I think it would be more sensible to have two files. Each with only one kind of swirl. Sure, it works properly but has no benefit in sense of reduced/redundant work
- A description like: "Big 17 logo with 8 colorsets" should be "Big 17 lines high logo" or "..swirl logo"?. The count of options is not important IMO. Pls look at the other files accordingly

Finally, don't you like some "info stuff" in the issue file, like kernel version and such? To add these to your VERY BIG logo/lettering is not sooo nice/simple from an esthetic point of view. But these small ones? If you "NO I don't want/like it", fine :-)

Hmm, would be good I would add ":tuRn>:"  tag or similar, see ToDo file. Then we could switch a logo in a file or enable disable logo or a lettering... Until then, we need more files.

**Comment by vidy007** [comment]
Good ideas!
> But..?
Just ignore it, ok?
> it would be more sensible to have two files.
Thinking about that, guess i will separate them later
> A description like: "Big 17 logo with 8 colorsets" should be "Big 17
lines high logo" or "..swirl logo"?.
How far can it go? Maybe better to focus on something else?
> If you "NO I don't want/like it", fine :-)
You're literally reading my mind.
> Hmm, would be good I would add ":tuRn>:" tag or similar, see ToDo file.
Then we could switch a logo in a file or enable disable logo or a
lettering...
That would be sooooooo so nice

пн, 4 нояб. 2024 г., 00:33 loh-tar ***@***.***>:

**Comment by loh-tar** [comment]
I did some clean up an  pushed a debian branch. I hope is useful. I made  some (not documented, sorry) changes, so look careful or use diff.

**Comment by vidy007** [comment]
Thank you for accepting those logos!

**Comment by loh-tar** [comment]
Of course, I will. I have to thank you for your contribution :-)

**Comment by vidy007** [comment]
Also, will there be other logos like Fedora, Ubuntu, etc?

пн, 4 нояб. 2024 г., 13:50 loh-tar ***@***.***>:

**Comment by loh-tar** [comment]
I am open to any kind of files, but it is not too likely that I will add any more :-)

Have you looked at the debian branch? Is everything to your satisfaction? 
I would still appreciate it if there were a few more explanations about the individual files, as previously explained.

>  ...":tuRn>:" tag or similar...
>> That would be sooooooo so nice

I'm about to have a look at it, but I don't know if I'll be successful.

**Comment by vidy007** [comment]
> it is not too likely that I will add any more :-)
I see. Welp, now i know how to make them :)

пн, 4 нояб. 2024 г., 15:10 loh-tar ***@***.***>:

**Comment by loh-tar** [comment]
> > ...":tuRn>:" tag or similar...
> > > That would be sooooooo so nice
> 
> I'm about to have a look at it, but I don't know if I'll be successful.

Done. See #7

**Comment by loh-tar** [comment]
Are you ok? You've become so quiet.
Please take a look at no. 7. I think it won't be long before I merge this, or something similar, with master.

**Comment by vidy007** [comment]
hi, i was busy far away from my home and now installing arch, so no news
for now

вс, 10 нояб. 2024 г., 15:57 loh-tar ***@***.***>:

**Comment by vidy007** [comment]
> Please take a look at no. 7. I think it won't be long before I merge this, or something similar, with master.

you mean updating my fork?

**Comment by vidy007** [comment]
Screenshot_20241115-110654_Firefox
oh god please no

**Comment by loh-tar** [comment]
Don't Panik!

I think you don't have to do anything. No need to rewrite from scratch. Just look at the three debian files in the razor branch ich you ok with that. I will later update the commit message slightly.
I think we can close here now.

**Comment by vidy007** [comment]
my fork thinks i didnt upload those deb arts lol

**Comment by vidy007** [comment]
> I think we can close here now.

close this request?

**Comment by loh-tar** [comment]
``> my fork thinks i didnt upload those deb arts lol

My git-skills are (also) very limited. You need to be careful when using "merge" or "rebase". My workflow omit "merge" completely, only "rebase" is nice to me. What I do is like this

```
git co new-feature
git rebase master
git co master
git rebase new-feature
```

> close this request?

Yes, I just hit the wrong button :-)

**Comment by loh-tar** [comment]
Your contribution is now in master ddf2a70 - Thank you!

**Comment by vidy007** [comment]
yay!
gonna make endavouros logos soon

пн, 18 нояб. 2024 г., 12:03 loh-tar ***@***.***>:

**Pull request closed without merging**
